from sqlmodel import SQLModel, Field
from typing import Optional
from datetime import datetime, timezone
import sqlalchemy as sa

def now_utc():
    return datetime.now(timezone.utc)

class NoteBase(SQLModel):
    title: str = Field(max_length=50, sa_type=sa.String) # *
    content: str = Field(max_length=500, sa_type=sa.String) # *


class Note(NoteBase, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    created_at: datetime = Field(default_factory=now_utc) # **
    updated_at: Optional[datetime] = Field(
        default_factory=now_utc,
        sa_column_kwargs={"onupdate": now_utc} # ***
    )

"""
* sa_type=sa.String - defined to remove AutoString() from autogenerated alembic migration file
** default_factory=now_utc - automatically sets default value of created_at = now_utc when new note is created
*** sa_column_kwargs={"onupdate": now_utc} - automatically sets updated_at = now_utc whenever the row is updated
"""